name: Build and Publish Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: cargo install --path .

      - name: Build binary
        run: cargo build --release --target ${{ matrix.os }} --bin wgrep

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Automated release for tag ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.os }}/release/wgrep
          asset_name: wgrep-${{ matrix.os }}-${{ github.ref }}
          asset_content_type: application/octet-stream
          github_token: ${{ secrets.GITHUB_TOKEN }}
